name: Cypress test runners

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      reference:
        description: 'Reference (a commit hash, a branch, or tag):'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Composer-Lock-Diff:
    runs-on: self-hosted
    name: wait-job
    steps:
      - name: Sleep for 5 minutes
        run: sleep 300s
        shell: bash